### ISSUE TITLE
only launches the vanilla game and doesn't connect to server's  

### ISSUE THREAD

**Issue by CTBALLER** [Dyvinia/KyberBrowser#1]
what the title says

**Comment by Dyvinia** [comment]
does the injected checkbox show up

**Comment by CTBALLER** [comment]
yes

**Comment by Dyvinia** [comment]
is there any error or anything indicating that kyber did not inject

**Comment by CTBALLER** [comment]
no it doesn't even run kyber

**Comment by CTBALLER** [comment]
ive run it again now it doesn't run at all

**Comment by CTBALLER** [comment]
could the datapath fix be the issue

**Comment by Dyvinia** [comment]
you dont need datapathfix unless youre on epicgamesstore

**Comment by CTBALLER** [comment]
well i use epic so okay

**Comment by Dyvinia** [comment]
you have to press the frosty button and launch the game through there with datapathfix

**Comment by CTBALLER** [comment]
it still doesn't work

**Comment by Dyvinia** [comment]
explain how, what is the exact order youre doing things and what exactly doesnt work. just saying 'it doesnt work' doesnt help anyone

**Comment by CTBALLER** [comment]
i run it as admin, then i click the frosty icon and run frosty through there, then i click the check mark and the launch my game with frosty, it opens the game with the mods but it doesn't connect to the kyber server and it does say inject

**Comment by Dyvinia** [comment]
you don't need to click the checkmark after clicking the frosty button

**Comment by Dyvinia** [comment]
@CTBALLER download the latest version and set the launchfix option to DatapathFix

**Comment by CTBALLER** [comment]
it still doesn't connect me to the server
