### ISSUE TITLE
when running the browser as admin it doesn't inject kyber 

### ISSUE THREAD

**Issue by CTBALLER** [Dyvinia/KyberBrowser#4]
not that big of an issue but when i dont run it as admin and open frosty with the browser it opens the one without admin

**Comment by Dyvinia** [comment]
?

**Comment by CTBALLER** [comment]
when running the browser as admin it doesn't eject kyber

**Comment by Dyvinia** [comment]
what does eject kyber even mean here? misspelling of inject or something else

**Comment by CTBALLER** [comment]
yeah i meant inject sorry
