### ISSUE TITLE
KyberBrowser refuses to change gamemode depsite setting it to something else.

### ISSUE THREAD

**Issue by dazzaXx** [Dyvinia/KyberBrowser#5]
Hello, I recently upgraded from v1.2.0 to v1.2.3 and noticed that now that it remembers the last config for hosting, (which in my case was co-op attack), even when changing it from coop attack to supremacy for example, it still loads up coop attack.

Don't know if this was just a fluke or not but despite trying multiple gamemodes, it always loaded up coop attack, I believe the maps changed alright, but I only tried the maps once.

EDIT: I have had to downgrade it back down to v1.2.0 for the time being.

**Comment by Dyvinia** [comment]
fixed in v1.2.4

**Comment by dazzaXx** [comment]
Thank You! Keep up the great work.
