### ISSUE TITLE
Fingerprint Verification Failed

### ISSUE THREAD

**Issue by almaazurius** [Dyvinia/KyberBrowser#6]
A friend is attempting to get things working, and has yet to be able to get the game to run. When attempting to join or host a server on KyberBrowser, the game attempts to load, but kicks back the error "You have been kicked from the server. Reason: Fingerprint verification failed. Please contact Kyber support for help." The only mods installed are Battlefront+ 9.1.
![Screenshot_3](https://github.com/Dyvinia/KyberBrowser/assets/99538051/5499fd61-7242-44f7-b503-0ba73c983b22)

**Comment by Dyvinia** [comment]
that has nothing to do with kyberbrowser, that is a kyber message meaning that you have to go to the kyber server for support

**Comment by almaazurius** [comment]
Alright, wasn't sure if that was an issue related to Browser or the main site. Thanks for the quick reply!
